name: Build Appsync Resolvers

on:
  push:
    branches:
    - master
    - develop
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Deps
      run: pip3.8 install appsync-schema-uploader appsync-resolver-uploader
    - name: Set env vars
      run: |
        echo "::set-env name=AWS_DEFAULT_REGION::us-east-1"
        if [ "${GITHUB_REF}" = "refs/heads/develop" ]; then
          echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets.AWS_ACCESS_KEY_ID_DEV }}"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}"
          echo "::set-env name=API_ID::${{ secrets.APPSYNC_API_ID_DEV }}"
        elif [ "${GITHUB_REF}" = "refs/heads/master" ]; then
          echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets.AWS_ACCESS_KEY_ID_PROD }}"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}"
          echo "::set-env name=API_ID::${{ secrets.APPSYNC_API_ID_DEV }}"
        elif [[ "${GITHUB_REF}" =~ ^refs/heads/release/([0-9]+\.)+[0-9]$ ]]; then
          echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}"
          echo "::set-env name=API_ID::${{ secrets.APPSYNC_API_ID_STAGE }}"
        else:
          echo "REF: ${GITHUB_REF}"
          echo "Not a buildable branch. Exiting"
        fi
        echo "REF: ${GITHUB_REF}"
    - name: Upload schema
      run: |
        python -m appsync_schema_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY} --api-id ${API_ID} --schema schema.graphql
    - name: Upload resolvers
      run: |
        SINGLE_RESPONSE="python -m appsync_resolver_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY} --api-id ${API_ID} --datasource-name dynamodb --response-mapping-template response_templates/single-result.vtl --request-mapping-template "
        MULTI_RESPONSE="python -m appsync_resolver_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY} --api-id ${API_ID} --datasource-name dynamodb --response-mapping-template response_templates/multi-result.vtl --request-mapping-template "
        LAMBDA_RESOLVER="python -m appsync_resolver_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY} --api-id ${API_ID} --datasource-name "

        # Queries
        $LAMBDA_RESOLVER kms_key_datasource --type-name Query --field-name ListKeys

        # Mutations
        $LAMBDA_RESOLVER kms_key_datasource --type Mutation --field-name PutKmsKey
        $SINGLE_RESPONSE request_templates/PutHl7InboundNode.vtl --type Mutation --field-name PutHl7InboundNode
        $SINGLE_RESPONSE request_templates/PutHl7OutboundNode.vtl --type Mutation --field-name PutHl7OutboundNode
        $SINGLE_RESPONSE request_templates/PutEdgeNode.vtl --type Mutation --field-name PutEdgeNode
        $SINGLE_RESPONSE request_templates/PutCustomNode.vtl --type Mutation --field-name PutEdgeNode
        $SINGLE_RESPONSE request_templates/PutEdge.vtl --type Mutation --field-name PutEdge
        $SINGLE_RESPONSE request_templates/PutHl7App.vtl --type Mutation --field-name PutHl7App
        $SINGLE_RESPONSE request_templates/PutEdgeApp.vtl --type Mutation --field-name PutEdgeApp
        $SINGLE_RESPONSE request_templates/PutTenant.vtl --type Mutation --field-name PutTenant

        # Subtypes
        $SINGLE_RESPONSE request_templates/X-tenant.vtl --type Hl7InboundNode --field-name tenant
        $SINGLE_RESPONSE request_templates/X-tenant.vtl --type Hl7OutboundNode --field-name tenant
        $SINGLE_RESPONSE request_templates/X-tenant.vtl --type EdgeNode --field-name tenant
        $SINGLE_RESPONSE request_templates/X-tenant.vtl --type CustomNode --field-name tenant
        $SINGLE_RESPONSE request_templates/X-tenant.vtl --type Edge --field-name tenant
        $SINGLE_RESPONSE request_templates/X-tenant.vtl --type Hl7App --field-name tenant
        $SINGLE_RESPONSE request_templates/X-tenant.vtl --type EdgeApp --field-name tenant
        $SINGLE_RESPONSE request_templates/X-tenant.vtl --type KMSKey --field-name tenant
        $SINGLE_RESPONSE request_templates/App-nodes.vtl --type App --field-name nodes
        $MULTI_RESPONSE request_templates/Node-source_edges.vtl --type Hl7InboundNode --field-name target_edges
        $MULTI_RESPONSE request_templates/Node-source_edges.vtl --type Hl7OutboundNode --field-name target_edges
        $MULTI_RESPONSE request_templates/Node-source_edges.vtl --type EdgeNode --field-name target_edges
        $MULTI_RESPONSE request_templates/Node-source_edges.vtl --type CustomNode --field-name target_edges
        $MULTI_RESPONSE request_templates/Node-target_edges.vtl --type Hl7InboundNode --field-name target_edges
        $MULTI_RESPONSE request_templates/Node-target_edges.vtl --type Hl7OutboundNode --field-name target_edges
        $MULTI_RESPONSE request_templates/Node-target_edges.vtl --type EdgeNode --field-name target_edges
        $MULTI_RESPONSE request_templates/Node-target_edges.vtl --type CustomNode --field-name target_edges
        $LAMBDA_RESOLVER kms_key_datasource --type-name Edge --field-name kms_key
