name: Build Appsync Resolvers

on:
  push:
    branches:
    - master
    - develop
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Deps
      run: pip3.8 install appsync-schema-uploader appsync-resolver-uploader appsync-function-uploader
    - name: Set env vars
      run: |
        echo "::set-env name=AWS_DEFAULT_REGION::us-east-1"
        if [ "${GITHUB_REF}" = "refs/heads/develop" ]; then
          echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets.AWS_ACCESS_KEY_ID_DEV }}"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}"
          echo "::set-env name=API_ID::${{ secrets.APPSYNC_API_ID_DEV }}"
        elif [ "${GITHUB_REF}" = "refs/heads/master" ]; then
          echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets.AWS_ACCESS_KEY_ID_PROD }}"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}"
          echo "::set-env name=API_ID::${{ secrets.APPSYNC_API_ID_DEV }}"
        elif [[ "${GITHUB_REF}" =~ ^refs/heads/release/([0-9]+\.)+[0-9]$ ]]; then
          echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}"
          echo "::set-env name=API_ID::${{ secrets.APPSYNC_API_ID_STAGE }}"
        else:
          echo "REF: ${GITHUB_REF}"
          echo "Not a buildable branch. Exiting"
        fi
        echo "REF: ${GITHUB_REF}"
    - name: Upload schema
      run: |
        python3.8 -m appsync_schema_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY} --api-id ${API_ID} --schema schema.graphql
    - name: Upload resolvers
      run: |
        SINGLE_RESPONSE="python3.8 -m appsync_resolver_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY} --api-id ${API_ID} --datasource-name dynamodb --response-mapping-template response_templates/single-result.vtl --request-mapping-template "
        DEFAULT="python3.8 -m appsync_resolver_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY} --api-id ${API_ID} --datasource-name dynamodb --response-mapping-template response_templates/default.vtl --request-mapping-template "
        LAMBDA_RESOLVER="python3.8 -m appsync_resolver_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY} --api-id ${API_ID} --datasource-name "
        SUBSCRIPTION="python3.8 -m appsync_resolver_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY} --api-id ${API_ID} --datasource-name none "
        PIPELINE="python3.8 -m appsync_resolver_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY}  --api-id ${API_ID} "
        FUNCTION="python3.8 -m appsync_function_uploader --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-access-key ${AWS_SECRET_ACCESS_KEY} --api-id ${API_ID} --datasource-name dynamodb --name "

        # Functions
        $FUNCTION test_for_nodes --description "Test if any nodes are attached to an app" --request-mapping-template request_templates/GetNodes_function.vtl --response-mapping-template response_templates/error_on_result.vtl
        $FUNCTION delete_app --description "Delete an app" --request-mapping-template request_templates/DeleteApp_function.vtl --response-mapping-template response_templates/default.vtl
        $FUNCTION test_for_source_edges --description "Test if any nodes are attached to an app" --request-mapping-template request_templates/GetSourceEdges_function.vtl --response-mapping-template response_templates/error_on_result.vtl
        $FUNCTION test_for_target_edges --description "Test if any nodes are attached to an app" --request-mapping-template request_templates/GetTargetEdges_function.vtl --response-mapping-template response_templates/error_on_result.vtl
        $FUNCTION delete_node --description "Delete an app" --request-mapping-template request_templates/DeleteNode_function.vtl --response-mapping-template response_templates/default.vtl
        $FUNCTION get_app --description "GetItem on an app" --request-mapping-template request_templates/ResetAppPassword_get_app_function.vtl --response-mapping-template response_templates/default.vtl
        $FUNCTION reset_password --description "Reset an app password" --request-mapping-template request_templates/ResetAppPassword_function.vtl --response-mapping-template response_templates/default.vtl

        # Queries
        $LAMBDA_RESOLVER kms_key_datasource --type-name Query --field-name ListKeys
        $DEFAULT request_templates/GetUsersForTenant.vtl --type-name Query --field-name GetUsersForTenant
        $DEFAULT request_templates/GetUser.vtl --type-name Query --field-name GetUser
        $DEFAULT request_templates/SearchNodes.vtl --type-name Query --field-name SearchNodes
        $DEFAULT request_templates/SearchApps.vtl --type-name Query --field-name SearchApps
        $DEFAULT request_templates/SearchEdges.vtl --type-name Query --field-name SearchEdges


        # Mutations
        $LAMBDA_RESOLVER kms_key_datasource --type Mutation --field-name PutKmsKey
        $LAMBDA_RESOLVER edge_datasource --type Mutation --field-name PutEdge
        $DEFAULT request_templates/PutNode.vtl --type Mutation --field-name PutHl7MLLPOutboundNode
        $DEFAULT request_templates/PutNode.vtl --type Mutation --field-name PutHl7MLLPInboundNode
        $DEFAULT request_templates/PutNode.vtl --type Mutation --field-name PutExternalNode
        $DEFAULT request_templates/PutApp.vtl --type Mutation --field-name PutExternalApp
        $DEFAULT request_templates/PutApp.vtl --type Mutation --field-name PutManagedApp
        $DEFAULT request_templates/PutTenant.vtl --type Mutation --field-name PutTenant
        $DEFAULT request_templates/AddUserToTenant.vtl --type Mutation --field-name AddUserToTenant
        $DEFAULT request_templates/StreamNotifications.vtl --type Mutation --field-name StreamNotifications
        $DEFAULT request_templates/DeleteEdge.vtl --type Mutation --field-name DeleteEdge
        $PIPELINE --type-name Mutation --field-name DeleteApp --response-mapping-template response_templates/default.vtl --request-mapping-template request_templates/DeleteApp_before.vtl --pipeline-config "test_for_nodes,dynamodb;delete_app,dynamodb"
        $PIPELINE --type-name Mutation --field-name DeleteNode --response-mapping-template response_templates/default.vtl --request-mapping-template request_templates/DeleteNode_before.vtl --pipeline-config "test_for_source_edges,dynamodb;test_for_target_edges,dynamodb;delete_node,dynamodb"
        $PIPELINE --type-name Mutation --field-name ResetAppPassword --response-mapping-template response_templates/default.vtl --request-mapping-template request_templates/ResetAppPassword_before.vtl --pipeline-config "get_app,dynamodb;reset_password,dynamodb"

        # Subtypes
        $DEFAULT request_templates/X-tenant.vtl --type Hl7MLLPInbound --field-name tenant
        $DEFAULT request_templates/X-tenant.vtl --type KMSKey --field-name tenant
        $DEFAULT request_templates/X-tenant.vtl --type Hl7MLLPOutboundNode --field-name tenant
        $DEFAULT request_templates/X-tenant.vtl --type Hl7MLLPInboundNode --field-name tenant
        $DEFAULT request_templates/X-tenant.vtl --type ExternalNode --field-name tenant
        $DEFAULT request_templates/X-tenant.vtl --type Edge --field-name tenant
        $DEFAULT request_templates/X-tenant.vtl --type ManagedApp --field-name tenant
        $DEFAULT request_templates/X-tenant.vtl --type ExternalApp --field-name tenant
        $DEFAULT request_templates/X-tenant.vtl --type User --field-name tenant
        $SINGLE_RESPONSE request_templates/Edge-source.vtl --type Edge --field-name source
        $SINGLE_RESPONSE request_templates/Edge-target.vtl --type Edge --field-name target

        # Nodes for apps
        $DEFAULT request_templates/App-nodes.vtl --type ManagedApp --field-name nodes
        $DEFAULT request_templates/App-nodes.vtl --type ExternalApp --field-name nodes


        # Edge resolvers for nodes
        $DEFAULT request_templates/Node-send_edges.vtl --type ExternalNode --field-name send_edges
        $SINGLE_RESPONSE request_templates/Node-receive_edges.vtl --type Hl7MLLPInboundNode --field-name send_edges
        $SINGLE_RESPONSE request_templates/Node-send_edges.vtl --type Hl7MLLPOutboundNode --field-name receive_edges
        $DEFAULT request_templates/Node-receive_edges.vtl --type ExternalNode --field-name receive_edges
        $LAMBDA_RESOLVER kms_key_datasource --type-name Edge --field-name kms_key

        # Subscriptions
        $SUBSCRIPTION --type Subscription --field-name onStreamNotifications --response-mapping-template response_templates/onStreamNotifications.vtl --request-mapping-template request_templates/onStreamNotifications.vtl
