name: Upload Appsync API

on:
  push:
    branches:
      - master
      - develop
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env vars
        run: |
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.ARTIFACTS_PIPELINES_ACCESS_KEY  }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.ARTIFACTS_PIPELINES_SECRET_KEY }}" >> $GITHUB_ENV
          echo "ARTIFACTS_BUCKET=${{ secrets.ARTIFACTS_S3 }}" >> $GITHUB_ENV

          if [ "${GITHUB_REF}" = "refs/heads/develop" ]; then
            echo "S3_PREFIX=${{ secrets.HL7_NINJA_VERSION }}-dev" >> $GITHUB_ENV
          elif [ "${GITHUB_REF}" = "refs/heads/master" ]; then
            echo "S3_PREFIX=${{ secrets.HL7_NINJA_VERSION }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" =~ ^refs/heads/release/([0-9]+\.)+[0-9]$ ]]; then
            echo "S3_PREFIX=${{ secrets.HL7_NINJA_VERSION }}-stage" >> $GITHUB_ENV
          else
            echo "REF: ${GITHUB_REF}"
            echo "Not a buildable branch. Exiting"
            exit 1
          fi
          echo "REF: ${GITHUB_REF}"
      - name: Upload
        run: aws s3 cp schema.graphql s3://$ARTIFACTS_BUCKET/$S3_PREFIX/appsync/ --content-type text/plain --sse
        if: ${{ success() }}
